/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ci.event;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author cluckeymccormick
 */
public class ViewApplet extends javax.swing.JApplet {

    private Controller controller;
    private View view;
    private Weather weather;
    
    /**
     * Initializes the applet MyApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        //Create the Connection Manager
        ConnectionManager conman = new ConnectionManager();
        //Create the Controller
        this.controller = new Controller(conman);
        //Create the View
        this.view = new View(conman);
        //Create the Weather
        this.weather = new Weather();
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        mainMenuPanel = new javax.swing.JPanel();
        mainMssgButton = new javax.swing.JButton();
        mainCrtEvtButton = new javax.swing.JButton();
        mainMngEvtButton = new javax.swing.JButton();
        mainAdminButton = new javax.swing.JButton();
        mainServLabel = new javax.swing.JLabel();
        mainScrollPane = new javax.swing.JScrollPane();
        mainServText = new javax.swing.JTextArea();
        mainLogoutButton = new javax.swing.JButton();
        messagePanel = new javax.swing.JPanel();
        messageSubjectScroll = new javax.swing.JScrollPane();
        messageSubjectList = new javax.swing.JList();
        messageSubjectLabel = new javax.swing.JLabel();
        messageAcceptButton = new javax.swing.JButton();
        messageRejectButton = new javax.swing.JButton();
        messageDeleteButton = new javax.swing.JButton();
        messageContentScroll = new javax.swing.JScrollPane();
        messageContentText = new javax.swing.JTextArea();
        messageSenderField = new javax.swing.JTextField();
        messageSenderLabel = new javax.swing.JLabel();
        messageSubjectSepLabel = new javax.swing.JLabel();
        messageSubjectSepField = new javax.swing.JTextField();
        messageContentLabel = new javax.swing.JLabel();
        messageTypeField = new javax.swing.JTextField();
        messageTypeLabel = new javax.swing.JLabel();
        messageMainButton = new javax.swing.JButton();
        createEvPanel = new javax.swing.JPanel();
        createNameLabel = new javax.swing.JLabel();
        createNameField = new javax.swing.JTextField();
        createDateLabel = new javax.swing.JLabel();
        createDateField = new javax.swing.JTextField();
        createWeatherPanel = new javax.swing.JPanel();
        weatherRainRadio = new javax.swing.JRadioButton();
        weatherCloudRadio = new javax.swing.JRadioButton();
        weatherSunRadio = new javax.swing.JRadioButton();
        weatherWarningLabel = new javax.swing.JLabel();
        weatherWarningField = new javax.swing.JTextField();
        createLocationLabel = new javax.swing.JLabel();
        createEvLocScroll = new javax.swing.JScrollPane();
        createEvLocList = new javax.swing.JList();
        createCreateButton = new javax.swing.JButton();
        createServerLabel = new javax.swing.JLabel();
        createServerScroll = new javax.swing.JScrollPane();
        createServerText = new javax.swing.JTextArea();
        createMainButton = new javax.swing.JButton();
        chooseEvPanel = new javax.swing.JPanel();
        chooseScroll = new javax.swing.JScrollPane();
        chooseEvList = new javax.swing.JList();
        chooseEvLabel = new javax.swing.JLabel();
        chooseChooseButton = new javax.swing.JButton();
        chooseMainButton = new javax.swing.JButton();
        manageEvPanel = new javax.swing.JPanel();
        manageWeatherPanel = new javax.swing.JPanel();
        manageRainRadio = new javax.swing.JRadioButton();
        manageCloudsRadio = new javax.swing.JRadioButton();
        manageSunRadio = new javax.swing.JRadioButton();
        manageWarningLabel = new javax.swing.JLabel();
        manageWarningField = new javax.swing.JTextField();
        manageUpdateButton = new javax.swing.JButton();
        manageDateField = new javax.swing.JTextField();
        manageDateLabel = new javax.swing.JLabel();
        manageLocLabel = new javax.swing.JLabel();
        manageNameField = new javax.swing.JTextField();
        manageNameLabel = new javax.swing.JLabel();
        manageLocCombo = new javax.swing.JComboBox();
        manageInviteButton = new javax.swing.JButton();
        manageInviteField = new javax.swing.JTextField();
        manageDeleteButton = new javax.swing.JButton();
        manageMainButton = new javax.swing.JButton();
        manageServerLabel = new javax.swing.JLabel();
        manageServerScroll = new javax.swing.JScrollPane();
        manageServerText = new javax.swing.JTextArea();
        loginPanel = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        loginUserField = new javax.swing.JTextField();
        loginPassLabel = new javax.swing.JLabel();
        loginPassField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginServLabel = new javax.swing.JLabel();
        loginScrollPane = new javax.swing.JScrollPane();
        loginServText = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(600, 440));

        cardContainer.setLayout(new java.awt.CardLayout());

        mainMenuPanel.setBackground(new java.awt.Color(239, 236, 202));
        mainMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Main Menu"));

        mainMssgButton.setText("Messages & Invites");
        mainMssgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMssgButtonActionPerformed(evt);
            }
        });

        mainCrtEvtButton.setText("Create Event");
        mainCrtEvtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainCrtEvtButtonActionPerformed(evt);
            }
        });

        mainMngEvtButton.setText("Manage Events");
        mainMngEvtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMngEvtButtonActionPerformed(evt);
            }
        });

        mainAdminButton.setText("Admin Options");

        mainServLabel.setText("Server Messages");

        mainServText.setEditable(false);
        mainServText.setColumns(20);
        mainServText.setLineWrap(true);
        mainServText.setRows(5);
        mainServText.setText("This will display a greeting of some kind. It'd also be nice to tell the user how many messages they have, or some other such information. \"Admin Options\" doesn't have to be included in the final product; that's where we'd put any debugging commands, buttons, and other such nonsense. ");
        mainScrollPane.setViewportView(mainServText);

        mainLogoutButton.setText("Logout");
        mainLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addComponent(mainCrtEvtButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMssgButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMngEvtButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addComponent(mainServLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mainLogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMssgButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainCrtEvtButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMngEvtButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainAdminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainServLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardContainer.add(mainMenuPanel, "main");

        messagePanel.setBackground(new java.awt.Color(239, 236, 202));
        messagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages & Invites"));

        messageSubjectList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        messageSubjectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        messageSubjectScroll.setViewportView(messageSubjectList);

        messageSubjectLabel.setText("Message Subjects");

        messageAcceptButton.setText("Accept Invite");

        messageRejectButton.setText("Reject Invite");

        messageDeleteButton.setText("Delete Message");

        messageContentText.setEditable(false);
        messageContentText.setColumns(20);
        messageContentText.setLineWrap(true);
        messageContentText.setRows(5);
        messageContentText.setText("The above list will present the subjects of all waiting messages. We can write custom code for this by right-clicking the list, going to properties, navigating to properties>model, and choose custom code.\n\nNotice the buttons found below. We'll need to separate the two type of messages: Invites, and Messages. Logic suggests that we'll want to have Message as a class, and Invite will inherit from it. Anyway, if the currently selected message is not an Invite type, we'll make the appropriate buttons to the lower left \"grey out\".");
        messageContentScroll.setViewportView(messageContentText);

        messageSenderField.setEditable(false);
        messageSenderField.setText("Example Text");
        messageSenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSenderFieldActionPerformed(evt);
            }
        });

        messageSenderLabel.setText("Sender ");

        messageSubjectSepLabel.setText("Subject");

        messageSubjectSepField.setEditable(false);
        messageSubjectSepField.setText("Example Subject");

        messageContentLabel.setText("Message Contents");

        messageTypeField.setEditable(false);
        messageTypeField.setText("Invite/Message - one of the two.");

        messageTypeLabel.setText("Message Type");

        messageMainButton.setText("Main Menu");
        messageMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageContentScroll)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addComponent(messageAcceptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageRejectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(messageMainButton))
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageSubjectScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageSubjectLabel)
                            .addComponent(messageContentLabel))
                        .addGap(18, 18, 18)
                        .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageSenderField)
                            .addComponent(messageTypeField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(messageSubjectSepField)
                            .addGroup(messagePanelLayout.createSequentialGroup()
                                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageTypeLabel)
                                    .addComponent(messageSenderLabel)
                                    .addComponent(messageSubjectSepLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageSubjectLabel)
                    .addComponent(messageTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addComponent(messageTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messageSenderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageSenderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messageSubjectSepLabel))
                    .addComponent(messageSubjectScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageSubjectSepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messageContentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(messageContentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageAcceptButton)
                    .addComponent(messageRejectButton)
                    .addComponent(messageDeleteButton)
                    .addComponent(messageMainButton))
                .addContainerGap())
        );

        cardContainer.add(messagePanel, "message");

        createEvPanel.setBackground(new java.awt.Color(239, 236, 202));
        createEvPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Event"));

        createNameLabel.setText("Event Name");

        createNameField.setText("jTextField4");

        createDateLabel.setText("Event Date");

        createDateField.setText("mm/dd/yyyy");

        createWeatherPanel.setBackground(new java.awt.Color(239, 236, 202));
        createWeatherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Weather Options"));

        weatherRainRadio.setSelected(true);
        weatherRainRadio.setText("Rain Allowed?");

        weatherCloudRadio.setSelected(true);
        weatherCloudRadio.setText("Clouds Allowed?");

        weatherSunRadio.setSelected(true);
        weatherSunRadio.setText("Sun Allowed?");

        weatherWarningLabel.setText("Warning Period");

        weatherWarningField.setText("X Days");

        javax.swing.GroupLayout createWeatherPanelLayout = new javax.swing.GroupLayout(createWeatherPanel);
        createWeatherPanel.setLayout(createWeatherPanelLayout);
        createWeatherPanelLayout.setHorizontalGroup(
            createWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createWeatherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weatherRainRadio)
                    .addComponent(weatherCloudRadio)
                    .addComponent(weatherWarningLabel)
                    .addGroup(createWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(weatherWarningField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(weatherSunRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createWeatherPanelLayout.setVerticalGroup(
            createWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createWeatherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weatherRainRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weatherCloudRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weatherSunRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weatherWarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weatherWarningField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createLocationLabel.setText("Event Location");

        createEvLocList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "CI Main Campus", "CI Thousand Oaks Campus", "Santa Rosa Island Research Station" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        createEvLocScroll.setViewportView(createEvLocList);

        createCreateButton.setText("Create Event");
        createCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCreateButtonActionPerformed(evt);
            }
        });

        createServerLabel.setText("Server Messages");

        createServerText.setColumns(20);
        createServerText.setRows(5);
        createServerScroll.setViewportView(createServerText);

        createMainButton.setText("Main Menu");
        createMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createEvPanelLayout = new javax.swing.GroupLayout(createEvPanel);
        createEvPanel.setLayout(createEvPanelLayout);
        createEvPanelLayout.setHorizontalGroup(
            createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createEvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createEvPanelLayout.createSequentialGroup()
                        .addComponent(createServerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createMainButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(createEvPanelLayout.createSequentialGroup()
                        .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(createEvPanelLayout.createSequentialGroup()
                                .addComponent(createServerLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createEvPanelLayout.createSequentialGroup()
                                .addComponent(createNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createEvPanelLayout.createSequentialGroup()
                                .addComponent(createWeatherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createEvLocScroll)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEvPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEvPanelLayout.createSequentialGroup()
                                                .addComponent(createLocationLabel)
                                                .addGap(129, 129, 129))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEvPanelLayout.createSequentialGroup()
                                                .addComponent(createCreateButton)
                                                .addGap(125, 125, 125)))))))
                        .addGap(18, 18, 18))))
        );
        createEvPanelLayout.setVerticalGroup(
            createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createEvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNameLabel)
                    .addComponent(createNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDateLabel)
                    .addComponent(createDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(createEvPanelLayout.createSequentialGroup()
                        .addComponent(createLocationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createEvLocScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createCreateButton))
                    .addComponent(createWeatherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(createEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createEvPanelLayout.createSequentialGroup()
                        .addComponent(createServerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createServerScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(createEvPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createMainButton)))
                .addContainerGap())
        );

        cardContainer.add(createEvPanel, "create");

        chooseEvPanel.setBackground(new java.awt.Color(239, 236, 202));
        chooseEvPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Event"));

        chooseEvList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        chooseScroll.setViewportView(chooseEvList);

        chooseEvLabel.setText("Your Events");

        chooseChooseButton.setText("Choose");
        chooseChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseChooseButtonActionPerformed(evt);
            }
        });

        chooseMainButton.setText("Main Menu");
        chooseMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseEvPanelLayout = new javax.swing.GroupLayout(chooseEvPanel);
        chooseEvPanel.setLayout(chooseEvPanelLayout);
        chooseEvPanelLayout.setHorizontalGroup(
            chooseEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseEvPanelLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(chooseEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseEvPanelLayout.createSequentialGroup()
                        .addGroup(chooseEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(chooseEvPanelLayout.createSequentialGroup()
                                .addComponent(chooseEvLabel)
                                .addGap(111, 111, 111)))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseEvPanelLayout.createSequentialGroup()
                        .addComponent(chooseChooseButton)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseEvPanelLayout.createSequentialGroup()
                        .addComponent(chooseMainButton)
                        .addContainerGap())))
        );
        chooseEvPanelLayout.setVerticalGroup(
            chooseEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseEvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseEvLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseChooseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(chooseMainButton)
                .addContainerGap())
        );

        cardContainer.add(chooseEvPanel, "choose");

        manageEvPanel.setBackground(new java.awt.Color(239, 236, 202));
        manageEvPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Event"));

        manageWeatherPanel.setBackground(new java.awt.Color(239, 236, 202));
        manageWeatherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Weather Options"));

        manageRainRadio.setSelected(true);
        manageRainRadio.setText("Rain Allowed?");

        manageCloudsRadio.setSelected(true);
        manageCloudsRadio.setText("Clouds Allowed?");

        manageSunRadio.setSelected(true);
        manageSunRadio.setText("Sun Allowed?");

        manageWarningLabel.setText("Warning Period");

        manageWarningField.setText("X Days");

        javax.swing.GroupLayout manageWeatherPanelLayout = new javax.swing.GroupLayout(manageWeatherPanel);
        manageWeatherPanel.setLayout(manageWeatherPanelLayout);
        manageWeatherPanelLayout.setHorizontalGroup(
            manageWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWeatherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageRainRadio)
                    .addComponent(manageCloudsRadio)
                    .addComponent(manageWarningLabel)
                    .addGroup(manageWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(manageWarningField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manageSunRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageWeatherPanelLayout.setVerticalGroup(
            manageWeatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWeatherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageRainRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCloudsRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageSunRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageWarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageWarningField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manageUpdateButton.setText("Update Event");

        manageDateField.setText("mm/dd/yyyy");

        manageDateLabel.setText("Event Date");

        manageLocLabel.setText("Event Location");

        manageNameField.setText("jTextField4");

        manageNameLabel.setText("Event Name");

        manageLocCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        manageInviteButton.setText("Invite User");

        manageInviteField.setText("jTextField10");

        manageDeleteButton.setText("Delete Event");

        manageMainButton.setText("Main Menu");
        manageMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMainButtonActionPerformed(evt);
            }
        });

        manageServerLabel.setText("Server Messages");

        manageServerText.setColumns(20);
        manageServerText.setRows(5);
        manageServerScroll.setViewportView(manageServerText);

        javax.swing.GroupLayout manageEvPanelLayout = new javax.swing.GroupLayout(manageEvPanel);
        manageEvPanel.setLayout(manageEvPanelLayout);
        manageEvPanelLayout.setHorizontalGroup(
            manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageEvPanelLayout.createSequentialGroup()
                        .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageEvPanelLayout.createSequentialGroup()
                                .addComponent(manageNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manageNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(manageDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageEvPanelLayout.createSequentialGroup()
                                .addComponent(manageWeatherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(manageEvPanelLayout.createSequentialGroup()
                                        .addComponent(manageInviteButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(manageInviteField))
                                    .addGroup(manageEvPanelLayout.createSequentialGroup()
                                        .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(manageLocLabel)
                                            .addComponent(manageLocCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(manageEvPanelLayout.createSequentialGroup()
                                                .addComponent(manageUpdateButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(manageDeleteButton)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18))
                    .addGroup(manageEvPanelLayout.createSequentialGroup()
                        .addComponent(manageServerLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageEvPanelLayout.createSequentialGroup()
                        .addComponent(manageServerScroll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageMainButton)
                        .addContainerGap())))
        );
        manageEvPanelLayout.setVerticalGroup(
            manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNameLabel)
                    .addComponent(manageNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageDateLabel)
                    .addComponent(manageDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageEvPanelLayout.createSequentialGroup()
                        .addComponent(manageLocLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageLocCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manageInviteButton)
                            .addComponent(manageInviteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manageUpdateButton)
                            .addComponent(manageDeleteButton)))
                    .addComponent(manageWeatherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(manageServerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageEvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageEvPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(manageMainButton))
                    .addComponent(manageServerScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );

        cardContainer.add(manageEvPanel, "manage\n");

        loginPanel.setBackground(new java.awt.Color(239, 236, 202));
        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        loginUserLabel.setText("User Name:");

        loginUserField.setText("default");
        loginUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserFieldActionPerformed(evt);
            }
        });

        loginPassLabel.setText("Password:");

        loginPassField.setText("default");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginServLabel.setText("Server Message");

        loginServText.setEditable(false);
        loginServText.setColumns(20);
        loginServText.setLineWrap(true);
        loginServText.setRows(5);
        loginServText.setTabSize(4);
        loginServText.setText("This box provides feedback information - like \"username doesn't exist\" or \"incorrect password\". I doubt we even need passwords. Of course, this brings up the question of how we make new users - perhaps we could have a \"Create User\" button next to the login button.");
        loginServText.setToolTipText("");
        loginScrollPane.setViewportView(loginServText);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginPassLabel)
                            .addComponent(loginUserLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(loginPassField)
                            .addComponent(loginUserField)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginServLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUserLabel)
                    .addComponent(loginUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPassLabel)
                    .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(23, 23, 23)
                .addComponent(loginServLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardContainer.add(loginPanel, "login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserFieldActionPerformed

    }//GEN-LAST:event_loginUserFieldActionPerformed

    private void mainMssgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMssgButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "message");
    }//GEN-LAST:event_mainMssgButtonActionPerformed

    private void messageSenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageSenderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageSenderFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "main");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void mainCrtEvtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainCrtEvtButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "create");
    }//GEN-LAST:event_mainCrtEvtButtonActionPerformed

    private void mainMngEvtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMngEvtButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "choose");
    }//GEN-LAST:event_mainMngEvtButtonActionPerformed

    private void mainLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLogoutButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "login");
    }//GEN-LAST:event_mainLogoutButtonActionPerformed

    private void createCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCreateButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "manage");
    }//GEN-LAST:event_createCreateButtonActionPerformed

    private void createMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMainButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "main");
    }//GEN-LAST:event_createMainButtonActionPerformed

    private void chooseChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseChooseButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "manage");
    }//GEN-LAST:event_chooseChooseButtonActionPerformed

    private void chooseMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseMainButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "main");
    }//GEN-LAST:event_chooseMainButtonActionPerformed

    private void manageMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMainButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "main");
    }//GEN-LAST:event_manageMainButtonActionPerformed

    private void messageMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageMainButtonActionPerformed
        CardLayout cl = (CardLayout)(cardContainer.getLayout());
        cl.show(cardContainer, "main");
    }//GEN-LAST:event_messageMainButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardContainer;
    private javax.swing.JButton chooseChooseButton;
    private javax.swing.JLabel chooseEvLabel;
    private javax.swing.JList chooseEvList;
    private javax.swing.JPanel chooseEvPanel;
    private javax.swing.JButton chooseMainButton;
    private javax.swing.JScrollPane chooseScroll;
    private javax.swing.JButton createCreateButton;
    private javax.swing.JTextField createDateField;
    private javax.swing.JLabel createDateLabel;
    private javax.swing.JList createEvLocList;
    private javax.swing.JScrollPane createEvLocScroll;
    private javax.swing.JPanel createEvPanel;
    private javax.swing.JLabel createLocationLabel;
    private javax.swing.JButton createMainButton;
    private javax.swing.JTextField createNameField;
    private javax.swing.JLabel createNameLabel;
    private javax.swing.JLabel createServerLabel;
    private javax.swing.JScrollPane createServerScroll;
    private javax.swing.JTextArea createServerText;
    private javax.swing.JPanel createWeatherPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPassField;
    private javax.swing.JLabel loginPassLabel;
    private javax.swing.JScrollPane loginScrollPane;
    private javax.swing.JLabel loginServLabel;
    private javax.swing.JTextArea loginServText;
    private javax.swing.JTextField loginUserField;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JButton mainAdminButton;
    private javax.swing.JButton mainCrtEvtButton;
    private javax.swing.JButton mainLogoutButton;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton mainMngEvtButton;
    private javax.swing.JButton mainMssgButton;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JLabel mainServLabel;
    private javax.swing.JTextArea mainServText;
    private javax.swing.JRadioButton manageCloudsRadio;
    private javax.swing.JTextField manageDateField;
    private javax.swing.JLabel manageDateLabel;
    private javax.swing.JButton manageDeleteButton;
    private javax.swing.JPanel manageEvPanel;
    private javax.swing.JButton manageInviteButton;
    private javax.swing.JTextField manageInviteField;
    private javax.swing.JComboBox manageLocCombo;
    private javax.swing.JLabel manageLocLabel;
    private javax.swing.JButton manageMainButton;
    private javax.swing.JTextField manageNameField;
    private javax.swing.JLabel manageNameLabel;
    private javax.swing.JRadioButton manageRainRadio;
    private javax.swing.JLabel manageServerLabel;
    private javax.swing.JScrollPane manageServerScroll;
    private javax.swing.JTextArea manageServerText;
    private javax.swing.JRadioButton manageSunRadio;
    private javax.swing.JButton manageUpdateButton;
    private javax.swing.JTextField manageWarningField;
    private javax.swing.JLabel manageWarningLabel;
    private javax.swing.JPanel manageWeatherPanel;
    private javax.swing.JButton messageAcceptButton;
    private javax.swing.JLabel messageContentLabel;
    private javax.swing.JScrollPane messageContentScroll;
    private javax.swing.JTextArea messageContentText;
    private javax.swing.JButton messageDeleteButton;
    private javax.swing.JButton messageMainButton;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JButton messageRejectButton;
    private javax.swing.JTextField messageSenderField;
    private javax.swing.JLabel messageSenderLabel;
    private javax.swing.JLabel messageSubjectLabel;
    private javax.swing.JList messageSubjectList;
    private javax.swing.JScrollPane messageSubjectScroll;
    private javax.swing.JTextField messageSubjectSepField;
    private javax.swing.JLabel messageSubjectSepLabel;
    private javax.swing.JTextField messageTypeField;
    private javax.swing.JLabel messageTypeLabel;
    private javax.swing.JRadioButton weatherCloudRadio;
    private javax.swing.JRadioButton weatherRainRadio;
    private javax.swing.JRadioButton weatherSunRadio;
    private javax.swing.JTextField weatherWarningField;
    private javax.swing.JLabel weatherWarningLabel;
    // End of variables declaration//GEN-END:variables
}
